# Generated by Django 2.2.1 on 2019-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default='', max_length=64)),
                ('private_key', models.CharField(default='', max_length=42)),
            ],
            options={
                'db_table': 'EthereumKeys',
            },
        ),
    ]
